/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lincomengineering.lincomroip;

public class lincomroipJNI {
  public final static native int initLincomRoIP();
  public final static native int destroyLincomRoIP();
  public final static native int connectLincomRoIP(String jarg1);
  public final static native int disconnectLincomRoIP();
  public final static native int sendmsgLincomRoIP(int jarg1, String jarg2);
}
